spring.application.name=crm

# Database Connection
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/scalina_crm
# Change these to your actual Mac postgres credentials (often just your mac username and empty password)
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Allow file uploads up to 5MB for receipts
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
